import { test, expect } from '@playwright/test';


test('Shohoz', async ({ page }) => {
  await page.goto('https://www.shohoz.com/')
  await page.waitForTimeout(6000)
  await page.click("//a[@title='Contact Us']")
  await page.waitForTimeout(3000)
  // await page.click("input[value='Send']", '({ force: true })')
  // await page.click({ force: true })
  // await page.waitForTimeout(3000)
  // await page.click("//a[@title='Contact Us']")
  // await page.waitForTimeout(3000)
  await page.click("(//div[@class='select-style'])[1]")
  await page.waitForTimeout(1000)
  await page.click("(//div[@class='select-style'])[1]")
  await page.waitForTimeout(1000)
  await page.fill("//input[@placeholder='Mahmud']", 'Mohammad Sohag')
  await page.waitForTimeout(2000)
  await page.click("(//div[@class='select-style']//select)[2]")
  await page.waitForTimeout(1000)
  await page.click("(//div[@class='select-style']//select)[2]")
  await page.waitForTimeout(1000)
  await page.fill("(//label[text()='Phone Number']/following::input)[1]", '01677997319')
  await page.waitForTimeout(2000)
  await page.fill("//input[@type='email']", 'sohagechologyx@gmail.com')
  await page.waitForTimeout(2000)
  await page.fill("//div[@class='col-full']//textarea[1]", 'Lets go')
  await page.waitForTimeout(1000)
  await page.click("(//img[@alt='Shohoz'])[1]")
  await page.waitForTimeout(6000)
  await page.click("//a[@title='Bus']")
  await page.waitForTimeout(6000)
  await page.fill("input[name='dest_from']", 'Chattogram')
  await page.fill("input[name='dest_to']", 'Dhaka')
  await page.click("input[name='doj']")
  await page.click("//a[contains(text(),'15')]")
  await page.click("input[name='dor']")
  await page.click("//a[contains(text(),'20')]")
  await page.click("button[type='submit']")
  
});